### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\\u2018' in position 593: ordinal not in range(128)

### ISSUE THREAD

**Issue by nmajin** [Azure/msrestazure-for-python#150]
Even after updating to 0.6.3 I am still seeing this exception:

```json
{
    "_ansible_parsed": false,
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {
        "ansible_delegated_host": "localhost",
        "ansible_host": "localhost"
    },
    "module_stderr": "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\n/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/users/awx/.ansible/tmp/ansible-tmp-1592313968.07-172203014694835/AnsiballZ_azure_rm_virtualmachine.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/users/awx/.ansible/tmp/ansible-tmp-1592313968.07-172203014694835/AnsiballZ_azure_rm_virtualmachine.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/users/awx/.ansible/tmp/ansible-tmp-1592313968.07-172203014694835/AnsiballZ_azure_rm_virtualmachine.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_vV4S86/__main__.py\", line 1795, in <module>\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_vV4S86/__main__.py\", line 1791, in main\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_vV4S86/__main__.py\", line 771, in __init__\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_vV4S86/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py\", line 308, in __init__\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_vV4S86/__main__.py\", line 1144, in exec_module\n  File \"/tmp/ansible_azure_rm_virtualmachine_payload_vV4S86/__main__.py\", line 1585, in create_or_update_vm\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrestazure/azure_exceptions.py\", line 192, in __str__\n    return str(self.error)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrestazure/azure_exceptions.py\", line 89, in __str__\n    error_str += \"\\nMessage: {}\".format(self._message)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\u2018' in position 593: ordinal not in range(128)\n",
    "changed": false,
    "module_stdout": "",
    "rc": 1,
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error"
}
```

This line appears to not be catching the exception:

../msrestazure/azure_exceptions.py
```python
error_str += "\nMessage: {}".format(self._message)
```

Is there a fix that can be done to account for other characters like u'\\u2018' that are throwing this exception? This is in result of a quota in the subscription being maxed out.

**Comment by lmazuel** [comment]
Writing the traceback in a readable manner:
```python
Traceback (most recent call last):
  File "/users/awx/.ansible/tmp/ansible-tmp-1592313968.07-172203014694835/AnsiballZ_azure_rm_virtualmachine.py", line 113, in <module>
    _ansiballz_main()
  File "/users/awx/.ansible/tmp/ansible-tmp-1592313968.07-172203014694835/AnsiballZ_azure_rm_virtualmachine.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/users/awx/.ansible/tmp/ansible-tmp-1592313968.07-172203014694835/AnsiballZ_azure_rm_virtualmachine.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_azure_rm_virtualmachine_payload_vV4S86/__main__.py", line 1795, in <module>
  File "/tmp/ansible_azure_rm_virtualmachine_payload_vV4S86/__main__.py", line 1791, in main
  File "/tmp/ansible_azure_rm_virtualmachine_payload_vV4S86/__main__.py", line 771, in __init__
  File "/tmp/ansible_azure_rm_virtualmachine_payload_vV4S86/ansible_azure_rm_virtualmachine_payload.zip/ansible/module_utils/azure_rm_common.py", line 308, in __init__
  File "/tmp/ansible_azure_rm_virtualmachine_payload_vV4S86/__main__.py", line 1144, in exec_module
  File "/tmp/ansible_azure_rm_virtualmachine_payload_vV4S86/__main__.py", line 1585, in create_or_update_vm
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrestazure/azure_exceptions.py", line 192, in __str__
    return str(self.error)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrestazure/azure_exceptions.py", line 89, in __str__
    error_str += "\nMessage: {}".format(self._message)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 593: ordinal not in range(128)
```

**Comment by lmazuel** [comment]
@nmajin I might need to do 
```python
u"\nMessage: {}".format(self._message)
```

This is Python 2.7, I'm not sure what is the type of `_message` here.

**Comment by nmajin** [comment]
Correct, python 2.7,.

So this line appears to fix this:
`error_str += "\nMessage: {}".format(self._message.encode('ascii', 'replace'))`

Here is the error we expect to see now:
```json
{
    "_ansible_parsed": true,
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {
        "ansible_delegated_host": "localhost",
        "ansible_host": "localhost"
    },
    "changed": false,
    "invocation": {
        "module_args": ""
    },
    "msg": "Error creating or updating virtual machine <<REDACTED>>> - Azure Error: OperationNotAllowed\nMessage: Operation could not be completed as it results in exceeding approved Total Regional Cores quota. Additional details - Deployment Model: Resource Manager, Location: <REDACTED>>, Current Limit: 10, Current Usage: 8, Additional Required: 4, (Minimum) New Limit Required: 12. Submit a request for Quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/%7B%22subId%22:%22********%22,%22pesId%22:%2206bfd9d3-516b-d5c6-5802-169c800dec89%22,%22supportTopicId%22:%22e12e3d1d-7fa0-af33-c6d0-3c50df9658a3%22%7D by specifying parameters listed in the ?Details? section for deployment to succeed. Please read more about quota limits at https://docs.microsoft.com/en-us/azure/azure-supportability/regional-quota-requests."
}
```

And here are the references:
- https://github.com/Azure/azure_preview_modules/issues/359
- https://github.com/ansible-collections/azure/issues/160

I assume a fix can be done and included in release 0.6.4?

**Comment by lmazuel** [comment]
This is not the right fix, we want to format a unicode string with another unicode string, see this:
```python
>>> t=u"éééé"
>>> "{}".format(t)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
>>> u"{}".format(t)
u'\xe9\xe9\xe9\xe9'
```

I believe the fix I was mentioning should solve the problem, I will try to do a PR. Could you test from a PR if I do one?
Thanks,

**Comment by nmajin** [comment]
I tried your solution and it didn’t work, same error as the original code. The only code that worked was what I last posted.

**Comment by lmazuel** [comment]
It might just mean there is more lines to fix :). That fast that you passed this line, and went further is encouraging. Re-encoding in ascii is loosing information that could be kept.

**Comment by lmazuel** [comment]
Hi @nmajin 
Would you be able to try this PR content?
https://github.com/Azure/msrestazure-for-python/pull/151

Thanks

**Comment by nmajin** [comment]
Yep, I will test this at some point today

**Comment by lmazuel** [comment]
Fixed in 0.6.4

**Comment by nmajin** [comment]
Sorry for the delay on testing this out, but looks like you may have done this and already pushed a version out with the fix.

I tried the 0.6.4 version and this fixes the issue for me.  Thanks!

**Comment by lmazuel** [comment]
@nmajin nice, thanks for the confirmation!
