### ISSUE TITLE
Unable to serialize a list

### ISSUE THREAD

**Issue by lmazuel** [Azure/msrestazure-for-python#16]
```python
Traceback (most recent call last):
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 243, in _serialize
    attributes = target_obj._attribute_map
AttributeError: 'list' object has no attribute '_attribute_map'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "d:\vsprojects\azure-sdk-for-python\azure-mgmt\tests\test_mgmt_machinelearning.py", line 279, in test_ml
    parameter_key = "Output mode"
  File "d:\vsprojects\azure-sdk-for-python\azure-mgmt-machinelearning\azure\mgmt\machinelearning\webservices\operations\web_services_operations.py", line 88, in create_or_update
    body_content = self._serialize.body(create_or_update_payload, 'WebService')
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 304, in body
    return self._serialize(data, data_type, **kwargs)
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 234, in _serialize
    target_obj, data_type, **kwargs)
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 433, in serialize_data
    return self._serialize(data, **kwargs)
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 257, in _serialize
    orig_attr, attr_type, **kwargs)
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 433, in serialize_data
    return self._serialize(data, **kwargs)
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 257, in _serialize
    orig_attr, attr_type, **kwargs)
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 433, in serialize_data
    return self._serialize(data, **kwargs)
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 257, in _serialize
    orig_attr, attr_type, **kwargs)
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 426, in serialize_data
    data, data_type[1:-1], **kwargs)
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 502, in serialize_dict
    value, dict_type, **kwargs)
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 433, in serialize_data
    return self._serialize(data, **kwargs)
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 276, in _serialize
    raise_with_traceback(SerializationError, msg, err)
  File "D:\VSProjects\msrest-for-python\msrest\exceptions.py", line 47, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "D:\VSProjects\msrest-for-python\msrest\serialization.py", line 243, in _serialize
    attributes = target_obj._attribute_map
msrest.exceptions.SerializationError: Attribute None in object list cannot be serialized., AttributeError: 'list' object has no attribute '_attribute_map'
```

From links here:
```python
class GraphParameter(Model):
    _validation = {
        'type': {'required': True},
        'links': {'required': True},
    }

    _attribute_map = {
        'description': {'key': 'description', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'links': {'key': 'links', 'type': '[GraphParameterLink]'},
    }

    def __init__(self, type, links, description=None):
        self.description = description
        self.type = type
        self.links = links
```

Creation:
```python
GraphParameter(
    type = None,
    links = [
      GraphParameterLink(
            node_id = "node2",
            parameter_key = "Trigonometric Function"
      ),
    ]
)
```

More details to come @annatisch, if you have specific question tell me.

**Comment by annatisch** [comment]
@lmazuel - ouch! Is this package public?

**Comment by lmazuel** [comment]
@annatisch nope, work in progress https://github.com/Azure/azure-sdk-for-python/pull/934

**Comment by lmazuel** [comment]
@annatisch I was able to find it, it's not where I initially thought. Take the branch use in the PR and write that:

```python
import azure.mgmt.machinelearning.webservices
from azure.mgmt.machinelearning.webservices.models import ExampleRequest
client = azure.mgmt.machinelearning.webservices.AzureMLWebServicesManagementClient(42, '42')

example_request = ExampleRequest(
            inputs = {
                "input1": [
                    [ "1", "2.3", "0.5", "4.3", "1.2" ],
                    [ "0", "0.5", "4.3", "1.2", "2.5" ],
                    [ "0", "4.3", "1.2", "6.5", "6.3" ],
                    [ "1", "7.8", "8.0", "2.3", "0.5" ],
                    [ "1", "1.3", "5.5", "2.2", "9.2" ]
                ]
            }
        )
client.web_services._serialize.body(example_request, 'ExampleRequest')
```

[ExampleRequest](https://github.com/lmazuel/azure-sdk-for-python/blob/machine_learning_mgmt/azure-mgmt-machinelearning/azure/mgmt/machinelearning/webservices/models/example_request.py) being defined:
```python
    _attribute_map = {
        'inputs': {'key': 'inputs', 'type': '{list}'},
        'global_parameters': {'key': 'globalParameters', 'type': '{object}'},
    }
```

It seems `{list}` has some problems to be serialized.

**Comment by annatisch** [comment]
@lmazuel - yes that has generated incorrectly.
It should be something like {[int]} for a dict where value is a list of integers; or {[[float]]} for a dict where that value is a list of lists of floats like you have above.
I'll try to reproduce with autorest .

**Comment by lmazuel** [comment]
@annatisch I think the point here is to say that list content can be anything, integer is just this specific example.

**Comment by lmazuel** [comment]
Fixed in Autorest
