### ISSUE TITLE
Unable to create VM's on Azure Stack

### ISSUE THREAD

**Issue by charliejllewellyn** [Azure/msrestazure-for-python#64]
I am using this module indirectly via Ansible. When creating a new VM I get an error because the storage endpoint is not set. The error I get is:

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_gH59XU/ansible_module_azure_rm_virtualmachine.py", line 1554, in <module>
    main()
  File "/tmp/ansible_gH59XU/ansible_module_azure_rm_virtualmachine.py", line 1551, in main
    AzureRMVirtualMachine()
  File "/tmp/ansible_gH59XU/ansible_module_azure_rm_virtualmachine.py", line 651, in __init__
    supports_check_mode=True)
  File "/tmp/ansible_gH59XU/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 285, in __init__
  File "/tmp/ansible_gH59XU/ansible_module_azure_rm_virtualmachine.py", line 716, in exec_module
    self._cloud_environment.suffixes.storage_endpoint,
  File "/usr/lib/python2.7/site-packages/msrestazure/azure_cloud.py", line 107, in __getattribute__
    "is not set but is used.".format(name))
msrestazure.azure_cloud.CloudSuffixNotSetException: The suffix 'storage_endpoint' for this cloud is not set but is used.

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_gH59XU/ansible_module_azure_rm_virtualmachine.py\", line 1554, in <module>\n    main()\n  File \"/tmp/ansible_gH59XU/ansible_module_azure_rm_virtualmachine.py\", line 1551, in main\n    AzureRMVirtualMachine()\n  File \"/tmp/ansible_gH59XU/ansible_module_azure_rm_virtualmachine.py\", line 651, in __init__\n    supports_check_mode=True)\n  File \"/tmp/ansible_gH59XU/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 285, in __init__\n  File \"/tmp/ansible_gH59XU/ansible_module_azure_rm_virtualmachine.py\", line 716, in exec_module\n    self._cloud_environment.suffixes.storage_endpoint,\n  File \"/usr/lib/python2.7/site-packages/msrestazure/azure_cloud.py\", line 107, in __getattribute__\n    \"is not set but is used.\".format(name))\nmsrestazure.azure_cloud.CloudSuffixNotSetException: The suffix 'storage_endpoint' for this cloud is not set but is used.\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

This is true as hitting the Azure Stack metadata endpoint does not return a storage_endpoint:

```
[root@91e9565d477d .azure]# curl https://management.azure.com/metadata/endpoints?api-version=2015-01-01 |jq
{
  "galleryEndpoint": "https://gallery.azure.com",
  "graphEndpoint": "https://graph.windows.net/",
  "portalEndpoint": "https://portal.azure.com",
  "authentication": {
    "loginEndpoint": "https://login.windows.net",
    "audiences": [
      "https://management.core.windows.net/",
      "https://management.azure.com/"
    ]
  }
}
```

This means this code never sets it https://github.com/Azure/msrestazure-for-python/blob/master/msrestazure/azure_cloud.py, meaning the cloud_enviornmnet set for Azure Stack looks like:

```
{'endpoints': {'active_directory': u'https://login.windows.net/',
               'active_directory_graph_resource_id': u'https://graph.windows.net/',
               'active_directory_resource_id': u'https://management.charliejllewellyngmail.onmicrosoft.com/xxxxxxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx',
               'batch_resource_id': None,
               'gallery': u'https://portal.local.azurestack.external:30015/',
               'management': 'https://management.local.azurestack.external',
               'resource_manager': 'https://management.local.azurestack.external',
               'sql_management': None},
 'name': 'https://management.local.azurestack.external',
 'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': None,
              'azure_datalake_store_file_system_endpoint': None,
              'keyvault_dns': None,
              'sql_server_hostname': None,
              'storage_endpoint': None}}
```

However, when dumping the environment for Azure we see the following:

```
{'endpoints': {'active_directory': 'https://login.microsoftonline.com',
               'active_directory_graph_resource_id': 'https://graph.windows.net/',
               'active_directory_resource_id': 'https://management.core.windows.net/',
               'batch_resource_id': 'https://batch.core.windows.net/',
               'gallery': 'https://gallery.azure.com/',
               'management': 'https://management.core.windows.net/',
               'resource_manager': 'https://management.azure.com/',
               'sql_management': 'https://management.core.windows.net:8443/'},
 'name': 'AzureCloud',
 'suffixes': {'azure_datalake_analytics_catalog_and_job_endpoint': 'azuredatalakeanalytics.net',
              'azure_datalake_store_file_system_endpoint': 'azuredatalakestore.net',
              'keyvault_dns': '.vault.azure.net',
              'sql_server_hostname': '.database.windows.net',
              'storage_endpoint': 'core.windows.net'}
```

Apologies if this is wrong place to raise this, if there is somewhere better please point me in that direction :)

**Comment by lmazuel** [comment]
@derekbekoe so, seems the metadata endpoint is not providing `storage_endpoint`, how the CLI is solving that? I don't find it in the code anything that guess this parameter if not there.
@bganapa what you think?

**Comment by bganapa** [comment]
As part of registering the azurestack cloud, the storage endpoint suffix needs to be explicitly specified.
Docs here https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-connect-cli 

ARM metadata endpoint does not provide this information.  We have a conversation with ARM team to simplify this experience

**Comment by bganapa** [comment]
just realizing that this is not filed in CLI repo. @shriramnat , we should speed up the work on python sdk profile support for azurestack and some samples

**Comment by lmazuel** [comment]
Thanks @bganapa 

@charliejllewellyn  @tstringer Ansible needs to be fixed:
https://github.com/ansible/ansible/blob/98260f9884fd265ea1037e3d58acf3cc50d2981a/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py#L798-L804

Replace this:
```python
if self.storage_account_name and not self.managed_disk_type:
      self.get_storage_account(self.storage_account_name)

      requested_vhd_uri = 'https://{0}.blob.{1}/{2}/{3}'.format(self.storage_account_name,
                                                                self._cloud_environment.suffixes.storage_endpoint,
                                                                self.storage_container_name,
                                                                self.storage_blob_name)
```

by this
```python
 if self.storage_account_name and not self.managed_disk_type:
       properties = self.get_storage_account(self.storage_account_name)

       requested_vhd_uri = '{0}{1}/{2}'.format(properties.primary_endpoints.blob,
                                               self.storage_container_name,
                                               self.storage_blob_name)
```

Closing this one, since nothing is wrong in SDK (at least not here :p)
