### ISSUE TITLE
Refresh_token doesn't seem to be working

### ISSUE THREAD

**Issue by lmazuel** [Azure/msrestazure-for-python#91]
From https://github.com/Azure/azure-sdk-for-python/issues/2467 created by @prburgu

It seems refresh_token is not working correct with latest azure sdk. If I pin, msrest and msrestazure to following version then it is working correctly.
```
msrestazure==0.4.26
msrest==0.4.27
```

Here is the error with latest azure sdk.
```
Traceback (most recent call last):
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/msrest/service_client.py", line 275, in send
    **kwargs)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/models.py", line 309, in prepare
    self.prepare_auth(auth, url)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/models.py", line 540, in prepare_auth
    r = auth(self)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests_oauthlib/oauth2_auth.py", line 35, in __call__
    http_method=r.method, body=r.body, headers=r.headers)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 193, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/prburgu/infra/acmcloud/cli.py", line 93, in <module>
    result = func(*func_args)
  File "/Users/prburgu/infra/acmcloud/accloud/subcommands/resources.py", line 73, in setup_docdb
    return setup_docdb(self, service_name)
  File "/Users/prburgu/infra/acmcloud/accloud/subcommands/utils/docdb_utils.py", line 15, in setup_docdb
    client.azure.resource_groups.create_or_update(client.config.resource_group_name, client.config.location)
  File "/Users/prburgu/infra/acmcloud/accloud/acazure/acazure_client.py", line 75, in resource_groups
    return ResourceGroupOperations(self)
  File "/Users/prburgu/infra/acmcloud/accloud/acazure/acazure_base.py", line 82, in __init__
    self._cache_all_resource_info()
  File "/Users/prburgu/infra/acmcloud/accloud/acazure/acazure_base.py", line 456, in _cache_all_resource_info
    for resource in self.resource_client().resources.list():
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/msrest/paging.py", line 121, in __next__
    self.advance_page()
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/msrest/paging.py", line 107, in advance_page
    self._response = self._get_next(self.next_link)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/resources_operations.py", line 361, in internal_paging
    request, header_parameters, **operation_config)
  File "/Users/prburgu/infra/acmcloud/accloud/acazure/acazure_clients.py", line 225, in send
    response = super(ACServiceClient, self).send(request, headers, content, **config)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/msrest/service_client.py", line 280, in send
    raise_with_traceback(TokenExpiredError, msg, err)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/msrest/exceptions.py", line 45, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/msrest/service_client.py", line 275, in send
    **kwargs)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/sessions.py", line 494, in request
    prep = self.prepare_request(req)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/sessions.py", line 437, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/models.py", line 309, in prepare
    self.prepare_auth(auth, url)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests/models.py", line 540, in prepare_auth
    r = auth(self)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/requests_oauthlib/oauth2_auth.py", line 35, in __call__
    http_method=r.method, body=r.body, headers=r.headers)
  File "/Users/prburgu/infra/acmcloud/miniconda_macos/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 193, in add_token
    raise TokenExpiredError()
msrest.exceptions.TokenExpiredError: Token expired or is invalid., TokenExpiredError: (token_expired)
```

**Comment by prburgu** [comment]
I'm doing something like this.

```
        context = adal.AuthenticationContext("https://login.windows.net")
        resource_url = "https://management.core.windows.net"
        code = context.acquire_user_code(resource_url, client_id)
        print(code["message"])
        token = context.acquire_token_with_device_code(resource_url, code, client_id)
```
Once I get the token, I'm generating tokens for different resources using refresh tokens as follows.

```
        resources = ["management", "vault", "graph"]
        headers = {"Content-Type": "application/x-www-form-urlencoded"}
        url = self.config.authority_host_url + "/{}/oauth2/token".format(self.config.aad_tenant)
        for resource in resources:
            if resource == "graph":
                resource_url = self.config.graph_endpoint
            elif resource == 'vault':
                resource_url = "https://vault.{}".format(self.config.azure_net_suffix)
            elif resource == 'management':
                resource_url = "https://management.core.{}/".format(self.config.windows_net_suffix)
            data = {
                "grant_type": "refresh_token",
                "client_id": token["_clientId"],
                "refresh_token": token["refreshToken"],
                "resource": resource_url
            }
            resp = requests.post(
                url,
                data=data,
                headers=headers
            )
```

Once I get these tokens, I cache them on the disk. When I need to use the tokens, I use it as follows.

```
                # msrestazure doesn't handle expires_on correctly, so convert it to expires_at if it isn't set already
                if token.get('expires_at') is None:
                    token['expires_at'] = token['expires_on']

                creds = AADTokenCredentials(token=token, resource=token['resource'])
```

**Comment by lmazuel** [comment]
I think I know what's happening, I introduced a regression specifically in `AADTokenCredentials`.
Will you be able to test a msrestazure from a branch? Just to be sure I fix it correctly

**Comment by lmazuel** [comment]
Ok, I really think I fixed your issue, and at the same time I took your `expires_at` fix ;)
I will suggest a branch here in the next hour, if you could check would make me more confident, but at worst I will release Monday.
Thanks!

**Comment by lmazuel** [comment]
@prburgu Fix in PR https://github.com/Azure/msrestazure-for-python/pull/92 and `refreshfix` branch.
I added your `token['expires_at'] = token['expires_on']` at the same time, should not be needed anymore.

Thanks!

**Comment by prburgu** [comment]
Thank you. This works great and fixes `expires_at`/`expires_on` issue as well.
